SecRuleEngine On
SecRequestBodyAccess On
SecRequestBodyLimit 52428800
SecRequestBodyNoFilesLimit 131072
SecRequestBodyLimitAction Reject
SecPcreMatchLimit 150000
SecPcreMatchLimitRecursion 150000

SecResponseBodyAccess Off
SecResponseBodyMimeType text/plain text/html text/xml
SecResponseBodyLimit 524288

SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLog /var/log/modsec_audit.log
SecAuditLogFormat JSON

SecRule MULTIPART_UNMATCHED_BOUNDARY "!@eq 0" \
    "id:'200003',phase:2,t:none,log,deny,msg:'Multipart parser detected unmatched boundary.'"

SecAction \
    "id:'900000',phase:1,nolog,pass,\
    setvar:tx.paranoia_level=1"

SecAction \
    "id:'900100',phase:1,nolog,pass,\
    setvar:tx.blocking_paranoia_level=1"

SecAction \
    "id:'900200',phase:1,nolog,pass,\
    setvar:tx.anomaly_score=0,\
    setvar:tx.anomaly_score_pl1=0,\
    setvar:tx.anomaly_score_pl2=0,\
    setvar:tx.anomaly_score_pl3=0,\
    setvar:tx.anomaly_score_pl4=0"

Include /etc/modsecurity.d/owasp-crs/crs-setup.conf
Include /etc/modsecurity.d/crs-exclusions.conf
Include /etc/modsecurity.d/owasp-crs/rules/*.conf
